apiVersion: v1
kind: ConfigMap
metadata:
  name: glews-config
  namespace: glews
  labels:
    app.kubernetes.io/name: glews
    app.kubernetes.io/part-of: glews
data:
  GLEWS_CONFIG: "config/global_watch.yaml"
  GLEWS_INTERVAL: "6"
  GLEWS_DASHBOARD_PORT: "8080"
  GLEWS_SMTP_PORT: "587"
