apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: glews-dashboard
  namespace: glews
  labels:
    app.kubernetes.io/name: glews
    app.kubernetes.io/component: dashboard
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: glews
      app.kubernetes.io/component: dashboard
